#!/bin/bash

cd ~
rm -f mandelbrot*.tgz
wget http://10.0.6.9:8080/jenkins/job/mandelbrot/ws/build/distributions/mandelbrot-0.1.0.tgz
wget http://10.0.6.9:8080/jenkins/job/mandelbrot/ws/dep/build/distributions/mandelbrot-dep-0.1.0.tgz
wget http://10.0.6.9:8080/jenkins/job/mandelbrot/ws/env/awsprod/search07/build/distributions/mandelbrot-env-awsprod-search07-0.1.0.tgz
cd /apps
rm -rf /apps/mandelbrot-0.1.0
tar -xzvf ~/mandelbrot-0.1.0.tgz 
tar -xzvf ~/mandelbrot-dep-0.1.0.tgz
tar -xzvf ~/mandelbrot-env-awsprod-search07-0.1.0.tgz

kill `cat /apps/logs/mandelbrot-awsprod-search07/mandelbrot-awsprod-search07.pid`
sleep 2
nohup /usr/bin/java -d64 -javaagent:/apps/newrelic/newrelic.jar -cp /apps/mandelbrot-0.1.0/lib/mandelbrot-0.1.0.jar:/apps/mandelbrot-0.1.0/lib/* -Xms31g -Xmx31g -XX:+UseG1GC -Dlog.level=INFO com.askme.mandelbrot.Launcher > /apps/mandelbrot-0.1.0/mandebrot.out &




