#!/bin/bash

cd ~
rm -f mandelbrot*.tgz
wget http://10.0.6.9:8080/jenkins/job/mandelbrot/ws/build/distributions/mandelbrot-0.1.0.tgz
wget http://10.0.6.9:8080/jenkins/job/mandelbrot/ws/dep/build/distributions/mandelbrot-dep-0.1.0.tgz
wget http://10.0.6.9:8080/jenkins/job/mandelbrot/ws/env/awsprod2/search09/build/distributions/mandelbrot-env-awsprod2-search09-0.1.0.tgz
cd /apps
rm -rf /apps/mandelbrot-0.1.0
tar -xzvf ~/mandelbrot-0.1.0.tgz 
tar -xzvf ~/mandelbrot-dep-0.1.0.tgz
tar -xzvf ~/mandelbrot-env-awsprod2-search09-0.1.0.tgz

kill `cat /apps/logs/mandelbrot-awsprod2-search09/mandelbrot-awsprod2-search09.pid`
sleep 5
nohup /usr/bin/java -d64 -cp /apps/mandelbrot-0.1.0/lib/mandelbrot-0.1.0.jar:/apps/mandelbrot-0.1.0/lib/* -Xms29g -Xmx29g -Dlog.level=INFO com.askme.mandelbrot.Launcher > /apps/mandelbrot-0.1.0/mandebrot.out &


